websocket.url:wss://ws.kraken.com/
websocket.subscription:{ \"event\": \"subscribe\", \"subscription\": { \"name\": \"book\"}, \"pair\": [ \"XBT/USD\", \"ETH/USD\" ]}
# For testing with added ETH/EUR pair
#websocket.subscription:{ \"event\": \"subscribe\", \"subscription\": { \"name\": \"book\"}, \"pair\": [ \"XBT/USD\", \"ETH/USD\", \"ETH/EUR\" ]}
# Specifies how long in minutes the reactive websocket client will consume messages
websocket.client.duration:10
print.fixed.delay:10000
