websocket.url:wss://ws.kraken.com/
websocket.subscription:{ \"event\": \"subscribe\", \"subscription\": { \"name\": \"book\"}, \"pair\": [ \"XBT/USD\", \"ETH/USD\" ]}
#For testing with added ETH/EUR pair
#websocket.subscription:{ \"event\": \"subscribe\", \"subscription\": { \"name\": \"book\"}, \"pair\": [ \"XBT/USD\", \"ETH/USD\", \"ETH/EUR\" ]}
print.fixed.delay:10000
